http:
  host: "localhost"
  port: "8000"
  frontend_origin: ["http://localhost:5173", "http://192.168.0.2:5173"]
  cookie_host: "localhost"

pg:
  pool_max: 15
  pg_url: "postgres://postgres:qwerty@postgres:5432/postgres?sslmode=disable"
  schema_url: "schema"

hasher:
  salt: "sdffwe235ef22jmjh78og2"

token_manager:
  signing_key: "qqvgfg5jk3fwioi2ifsd"
  atttl: 5s
  rtttl: 43800m

logger:
  log_level: "debug"

email_sender:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  from: "anspace.world@gmail.com"