http:
  host: "localhost"
  port: "8000"

pg:
  pool_max: 15
  pg_url: "postgres://postgres:qwerty@localhost:5432/postgres?sslmode=disable"
  schema_url: "schema"

hasher:
  salt: "sdffwe235ef22jmjh78og2"

token_manager:
  signing_key: "qqvgfg5jk3fwioi2ifsd"
  atttl: 15m
  rtttl: 2880m

logger:
  log_level: "debug"
