# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the Go documentation
# (https://docs.platform.sh/languages/go.html#supported-versions)
# to find the supported versions for the 'golang' type.
type: "golang:1.23"

hooks:
  build: |
    # Modify this line if you want to build differently or use an alternate name for your executable.
    go build -tags netgo -ldflags '-s -w' -o app ./cmd

web:
  upstream:
    socket_family: tcp
    protocol: http

  commands:
    # If you change the build output in the build hook above, update this line as well.
    start: ./app

  locations:
    /:
      # Route all requests to the Go app, unconditionally.
      allow: false
      passthru: true

disk: 1024
source:
  root: backend
