version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - 5432:5432

  app:
    build: .
    container_name: app
    image: app
    ports:
      - 8080:8080
    depends_on:
      - postgres
