version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASS}"
      POSTGRES_DB: "${PG_NAME}"
    ports:
      - 5432:5432

  app:
    build: .
    container_name: app
    image: app
    ports:
      - 8080:8080
    depends_on:
      - postgres
