name: CI
on:
  push:
    branches:
      - main

jobs:
  tests:
    name: runner / tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Unit Tests
        run: "cd backend
          go test \
          -v \
          -short \
          -count=1 \
          -race \
          -coverprofile=coverage.txt \
          ./..."
      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)

      - name: Integration tests
        run: "cd backend
        docker-compose \
        -f docker-compose.integration.yml up \
          --build \
          --abort-on-container-exit \
          --exit-code-from integration"
