name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github'

jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with: 
          workdir: backend

  tests:
    name: runner / tests
    runs-on: ubuntu-latest
    needs: [golangci-lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
          cache-dependency-path: |
             backend/go.sum

      - name: Unit Tests
        working-directory: backend
        run: "
          go test \
          -v \
          -short \
          -count=1 \
          -race \
          -coverprofile=coverage.txt \
          ./..."

      - name: Integration tests
        working-directory: backend
        run: "
          docker-compose \
          -f docker-compose.integration.yml up \
          --build \
          --abort-on-container-exit \
          --exit-code-from integration"
